spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: test1357
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  server:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

org:
  zerock:
    upload:
      path: upload

logging:
  level:
    org:
      springframework:
        security:
          web: trace